### ISSUE TITLE
Persistent group titles get mixed up

### ISSUE THREAD

**Issue by anthonybilinski** [TokTok/c-toxcore#1285] opened 2019-01-05 06:17 UTC
Follow up from https://github.com/qTox/qTox/issues/5482#issuecomment-451631287

Low reproducibility of receiving a `tox_callback_conference_title` a while after all groups are loaded, changing one of my loaded group titles to that of another group. The title change is from a peer that does not exist, giving `TOX_ERR_CONFERENCE_PEER_QUERY_PEER_NOT_FOUND` when queried.

@zugz FYI.

**Comment by zugz** [comment] 2019-01-05 21:10
* Friday, 2019-01-04 at 22:17 -0800 - Anthony Bilinski <notifications@github.com>:

>changing one of my loaded group titles to that of another group.

Thanks for the report. Could you check if #1287 fixes it?

**Comment by anthonybilinski** [comment] 2019-01-07 07:43
Tested and repro'd the original issue unfortunately.

For the commit message of "Avoid sending group messages to a peer before we have its group number" I just want to reiterate that there are no other peers in this group that's having its title changed, and I haven't changed the name (of any of my groups) so I'm not sure that the commit message matches the symptoms I'm seeing.

**Comment by zugz** [comment] 2019-01-07 20:31
* Sunday, 2019-01-06 at 23:43 -0800 - Anthony Bilinski <notifications@github.com>:

>Tested and repro'd the original issue unfortunately.

Sorry, I should have specified: it isn't you who needs to run the 
patched version, but rather the users in the group which has the title 
to which the title of your 0th group is changed. If I'm right about the 
cause, the problem is that they are telling you the title of that group, 
but doing so before they know your group number for the group, so using 
the default value of 0 instead, causing your client to understand them 
as having changed the title of group 0. Your client will honour this 
request if it is trying to reconnect in group 0 to that peer.

This fits your symptoms if I understand them correctly. I expect the PR 
will fix this bug. Certainly it fixes an error in the code, so should be 
merged in any case, but it would be good to confirm that it fixes this 
bug. So if it's feasible for you to get your friends to use the PR 
version so you can test it, that would be great.

**Comment by anthonybilinski** [comment] 2019-01-08 09:38
Ok that makes more sense, the group that the title was being changed to had 6 members, I think 5 of which were using qTox and 1 Toxic. I unfortunately lost all the peers in the group and the network I was on and haven't been able to repro the bug since with 6 clients running locally. I won't be able to test on that network any more so it's probably not worth blocking the PR on my repro when the fix matches the symptoms I saw.

**Closed** 2019-01-08 11:39 UTC
