### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by KORuL** [TokTok/c-toxcore#1274] opened 2018-12-02 19:01 UTC
Build error/ First error is missing libsodium! After `sudo apt-get install libsodium-dev;`  next error is:

```
user@ubuntu:~/c-toxcore-0.2.8/_build$ make
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/crypto_core.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/crypto_core_mem.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/logger.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/mono_time.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/network.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/state.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/util.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/DHT.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/LAN_discovery.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/ping.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/ping_array.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/TCP_client.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/TCP_connection.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/TCP_server.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/list.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/net_crypto.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/onion.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/onion_announce.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/onion_client.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/friend_connection.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/friend_requests.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/Messenger.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/group.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/tox_api.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxcore/tox.c.o
[  1%] Building C object CMakeFiles/toxcore_static.dir/toxencryptsave/toxencryptsave.c.o
[  1%] Linking C static library libtoxcore.a
[  1%] Built target toxcore_static
Scanning dependencies of target misc_tools
[  1%] Building C object CMakeFiles/misc_tools.dir/testing/misc_tools.c.o
[  1%] Linking C static library libmisc_tools.a
[  1%] Built target misc_tools
Scanning dependencies of target save-generator
[  1%] Building C object CMakeFiles/save-generator.dir/other/fun/save-generator.c.o
[  1%] Linking C executable save-generator
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `public_key_cmp':
crypto_core.c:(.text+0x1f): undefined reference to `crypto_verify_32'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `encrypt_precompute':
crypto_core.c:(.text+0x178): undefined reference to `crypto_box_beforenm'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `encrypt_data_symmetric':
crypto_core.c:(.text+0x2e2): undefined reference to `crypto_box_afternm'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `decrypt_data_symmetric':
crypto_core.c:(.text+0x49f): undefined reference to `crypto_box_open_afternm'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `crypto_new_keypair':
crypto_core.c:(.text+0x81f): undefined reference to `crypto_box_keypair'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `crypto_derive_public_key':
crypto_core.c:(.text+0x844): undefined reference to `crypto_scalarmult_curve25519_base'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `crypto_sha256':
crypto_core.c:(.text+0x872): undefined reference to `crypto_hash_sha256'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `crypto_sha512':
crypto_core.c:(.text+0x8a0): undefined reference to `crypto_hash_sha512'
/usr/bin/ld: libtoxcore.a(crypto_core.c.o): in function `random_bytes':
crypto_core.c:(.text+0x8c6): undefined reference to `randombytes'
/usr/bin/ld: libtoxcore.a(crypto_core_mem.c.o): in function `crypto_memzero':
crypto_core_mem.c:(.text+0x1f): undefined reference to `sodium_memzero'
/usr/bin/ld: libtoxcore.a(crypto_core_mem.c.o): in function `crypto_memcmp':
crypto_core_mem.c:(.text+0x4d): undefined reference to `sodium_memcmp'
/usr/bin/ld: libtoxcore.a(network.c.o): in function `networking_at_startup':
network.c:(.text+0xdd3): undefined reference to `sodium_init'
/usr/bin/ld: libmisc_tools.a(misc_tools.c.o): in function `use_test_rng':
misc_tools.c:(.text+0x6f3): undefined reference to `randombytes_set_implementation'
collect2: error: ld returned 1 exit status
make[2]: *** [save-generator] Error 1
make[1]: *** [CMakeFiles/save-generator.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by nurupo** [comment] 2018-12-03 11:57
Do a clean build. Remove `_build`, create it again and run the cmake and make commands.

**Comment by zerofancy** [comment] 2019-10-10 18:17
I also encountered the same problem, is it solved?

**Comment by nurupo** [comment] 2019-10-10 18:43
You are missing libsodium, install it.

**Comment by zerofancy** [comment] 2019-10-11 03:27
I tried `sudo apt-get install libsodium-dev` and also tried to compile and install `libsodium` directly, but that didn't help.

```
[ 83%] Building C object CMakeFiles/toxcore_shared.dir/toxcore/Messenger.c.o
[ 84%] Building C object CMakeFiles/toxcore_shared.dir/toxcore/group.c.o
[ 86%] Building C object CMakeFiles/toxcore_shared.dir/toxcore/tox_api.c.o
[ 88%] Building C object CMakeFiles/toxcore_shared.dir/toxcore/tox.c.o
[ 89%] Building C object CMakeFiles/toxcore_shared.dir/toxencryptsave/toxencryptsave.c.o
[ 91%] Linking C shared library libtoxcore.so
[ 91%] Built target toxcore_shared
Scanning dependencies of target misc_tools
[ 93%] Building C object CMakeFiles/misc_tools.dir/testing/misc_tools.c.o
[ 94%] Linking C static library libmisc_tools.a
[ 94%] Built target misc_tools
Scanning dependencies of target DHT_bootstrap
[ 96%] Building C object CMakeFiles/DHT_bootstrap.dir/other/DHT_bootstrap.c.o
[ 98%] Building C object CMakeFiles/DHT_bootstrap.dir/other/bootstrap_node_packets.c.o
[100%] Linking C executable DHT_bootstrap
libtoxcore.a(network.c.o)：在函数‘networking_at_startup’中：
network.c:(.text+0xe1d)：对‘sodium_init’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘public_key_cmp’中：
crypto_core.c:(.text+0x72)：对‘crypto_verify_32’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘encrypt_precompute’中：
crypto_core.c:(.text+0x1cb)：对‘crypto_box_beforenm’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘encrypt_data_symmetric’中：
crypto_core.c:(.text+0x2e6)：对‘crypto_box_afternm’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘decrypt_data_symmetric’中：
crypto_core.c:(.text+0x47e)：对‘crypto_box_open_afternm’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘crypto_new_keypair’中：
crypto_core.c:(.text+0x828)：对‘crypto_box_keypair’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘crypto_derive_public_key’中：
crypto_core.c:(.text+0x84d)：对‘crypto_scalarmult_curve25519_base’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘crypto_sha256’中：
crypto_core.c:(.text+0x87b)：对‘crypto_hash_sha256’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘crypto_sha512’中：
crypto_core.c:(.text+0x8a9)：对‘crypto_hash_sha512’未定义的引用
libtoxcore.a(crypto_core.c.o)：在函数‘random_bytes’中：
crypto_core.c:(.text+0x8cf)：对‘randombytes’未定义的引用
libtoxcore.a(crypto_core_mem.c.o)：在函数‘crypto_memzero’中：
crypto_core_mem.c:(.text+0x1f)：对‘sodium_memzero’未定义的引用
libtoxcore.a(crypto_core_mem.c.o)：在函数‘crypto_memcmp’中：
crypto_core_mem.c:(.text+0x4d)：对‘sodium_memcmp’未定义的引用
libmisc_tools.a(misc_tools.c.o)：在函数‘use_test_rng’中：
misc_tools.c:(.text+0x6f2)：对‘randombytes_set_implementation’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/DHT_bootstrap.dir/build.make:125: recipe for target 'DHT_bootstrap' failed
make[2]: *** [DHT_bootstrap] Error 1
CMakeFiles/Makefile2:1043: recipe for target 'CMakeFiles/DHT_bootstrap.dir/all' failed
make[1]: *** [CMakeFiles/DHT_bootstrap.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nurupo** [comment] 2019-10-11 03:47
Hm, perhaps you don't have `pkg-config` installed then, cmake uses it for finding dependencies like libsodium, which would explain why libsodium is not getting linked.

**Comment by nurupo** [comment] 2019-10-11 03:50
Speaking of binary packages, [toxcore is packaged in Ubuntu 18.10 and 19.04](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=toxcore).

**Comment by nurupo** [comment] 2019-10-13 22:54
Closing the issue since the original poster hasn't replied anything in a while, the issue is not reproducible on my machine and CI configurations, and @zerofancy seems to have gotten his issue resolved judging by the thumbs-up.

**Closed by nurupo** 2019-10-13 22:54 UTC

**Comment by Joey5460** [comment] 2020-05-30 03:38
For Fedora 31, I also set "export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" where libsodium is installed.  A reference here https://people.freedesktop.org/~dbn/pkg-config-guide.html.

**Comment by nurupo** [comment] 2020-05-30 04:28
@Joey5460 `/usr/local` is for self-built software, not for distro-packaged, so that's not Fedora's libsodium you have in there. pkg-config doesn't look in `/usr/local` by default. Obviously, if you have toxcore dependencies installed all over your system, you need to tell pkg-config where to look for them in order to build toxcore, which is done using `PKG_CONFIG_*` env variables.

**Comment by Joey5460** [comment] 2020-06-03 15:32
@nurupo  Great, thanks for your explanation.
