### ISSUE TITLE
Tox doesn't reconnect after internet connection interruption

### ISSUE THREAD

**Issue by ovalseven8** [TokTok/c-toxcore#240] opened 2016-11-05 15:56 UTC
Seems like the clients have to reconnect manually because it's not done by toxcore automatically.

For more information look here:
https://github.com/qTox/qTox/issues/1560

**Comment by vladimiry** [comment] 2016-11-15 22:17
Looks like duplicate of this https://github.com/TokTok/c-toxcore/issues/237

**Comment by iphydf** [comment] 2016-11-15 22:22
It's different. IIUC, this is about our own connection not being re-established, while #237 is about friends not coming online although we are ourselves online.

**Comment by shalnoff** [comment] 2017-07-14 22:51
quite annoying issue. It is necessary to click reconnect each time after laptop suspension / hibernation or when internet connection interrupted. And my friends see me offline until I recall that and check Tox for connection loss.

**Comment by toxtox** [comment] 2017-11-05 10:52
I made a some tests for reproducing this issue with Antox and TRIfA 1.0.8  and 1.0.9.
TRifA 1.0.8 and Antox-Versions older than Jan./Feb. 2017 never reconnected automatically after interruption of connection:
https://github.com/zoff99/ToxAndroidRefImpl/issues/17

Then zoff99 applied a patch in TRifA 1.0.9 (I guess the same that he applied in Antox before):
https://github.com/zoff99/ToxAndroidRefImpl/commit/0670c73d67311afbe99cc15fead24f3e1c9fcaaa

Now TRifa 1.0.9 and 1.0.10. is acting the same way as newer Antox-Versions and always reconnects automatically after the **first** interruption but **NEVER** after the **second** interruption (I used 5minute-interruptions but this behavior can be seen even with shorter interruptions)
https://github.com/zoff99/ToxAndroidRefImpl/issues/25

**=> This issue should be solved on c-toxcore that all c-toxcore based clients run reliable**

**Closed** 2017-11-25 18:39 UTC
Labels: CAT:bug, MOD:Network, P:high
