### ISSUE TITLE
Fix file transfers

### ISSUE THREAD

**Issue by yurivict** [TokTok/c-toxcore#438] opened 2017-01-16 02:26 UTC
Currently file transfers are broken. The qTox bug https://github.com/qTox/qTox/issues/3537 says "upstream", but there is no corresponding bug here.

This is a major problem, happens even with standalone transfers. Offline/online interruption and transfer concurrency are certainly breaking factors.

**Comment by GrayHatter** [comment] 2017-01-16 02:33
That's not a toxcore bug.

There are parts of that issue that could be fixed in toxcore, (namely; only parallel transfers instead of series). But using qTox to Dx this as a toxcore issue is problematic. uTox doesn't have this issue, and while files are still transferred one by one, the status of files, as well as file resuming works well.

**Comment by yurivict** [comment] 2017-01-16 03:04
They should work concurrently too.

**Comment by zoff99** [comment] 2017-01-16 09:01
allowing multiple FTs in toxcore would be good. hope this feature will soon happen

**Comment by zoff99** [comment] 2017-01-23 12:41
also it sure is a toxcore bug, if filetransfers are "forgotten" every time a friend goes offline. when both nodes are still running and did not shutdown. filetransfer structures should only be "forgotten" if a tox node really shuts down. otherwise just keep it im memory, where they already are

**Comment by GrayHatter** [comment] 2017-01-23 21:55
> just keep it im memory, where they already are 

That sounds like a great way to cause a memory leak. Resetting file transfers is exactly the thing toxcore should be doing. Toxcore does data transfer, not data saving/storage.

**Comment by zoff99** [comment] 2017-01-24 09:23
thats not true, if you start 100 filetransfers and keep online you need the exact same memory, as if you go offline and online again.
where is the memory leak? where is data saving/storing? its already in there in memory.

**Comment by GrayHatter** [comment] 2017-01-24 09:44
Sure, but how long should toxcore keep that data for? What happens if you
delete the file while the friend is offline? Or if the file changes. Should
toxcore save that data through restarts too? What should toxcore do if the
friend doesn't accept the 'restarted' transfer?

**Comment by zoff99** [comment] 2017-01-24 10:14
i am just thinking about mobile devices. they will appear to be offline very often. every few minutes even.
toxcore should not save that data when shutting down. also not hold that data too long. just a bit.
maybe a few minutes.
"What should toxcore do if the friend doesn't accept the 'restarted' transfer" -> i guess the same as not accepting a normal transfer. since a restart would not be different from a normal transfer. what do clients do now when this happens?

**Comment by yurivict** [comment] 2017-02-06 22:32
I am looking at why Antox on my LAN fails to send the file transfer to qTox on FreeBSD on the same LAN.

The callback is connected:
```
tox_callback_file_chunk_request(tox, CoreFile::onFileDataCallback);
```

But it only reads ~0.035 of the file and hangs. The callback isn't called, the data doesn't arrive from the socket.

What do I do now?

**Comment by zoff99** [comment] 2017-02-07 09:55
@yurivict what version of android are you using? try it with the latetest release or the 0.25.1 development version

**Comment by LittleVulpix** [comment] 2017-02-07 10:22
Once upon a time I paid $1k to get filetransfers in toxcore fixed. And they were, they actually worked really well, maybe with the exception of some edge cases like a person running via tor while connected through airport wifi. And the world was good.

But it all changed when the fire nation attacked. Well actually I have no idea why it all changed, but for the past year or so, filetransfers have been useless. Even on fast connections, you often get a case where (I assume due to tcp->udp switch), the transfer dies. Or it just dies randomly. Or the speed is a fraction of what it should be. Or the speed is like an ocean wave; instead of being high, it goes to super high, chokes the line, back to like 1KiB/s and then again back to super high.

A fix for file transfers would be amazing.

**Comment by yurivict** [comment] 2017-02-07 17:52
@zoff99 I experienced the problem with both very old and very new Android versions. If the device is older than 1-2 years, it is often not upgradable.

**Comment by zoff99** [comment] 2017-02-07 18:23
@yurivict sorry i corrected the error.
what version of **Antox** are you using? try it with the latetest release or the 0.25.1 development version

**Comment by yurivict** [comment] 2017-02-07 18:32
Antox version is 0.24.422.

**Comment by zoff99** [comment] 2017-02-07 18:53
can you try with the latest antox (should be 0.25.x)

**Comment by yurivict** [comment] 2017-02-07 19:08
Are there instructions how to install the latest dev apk? Google play only has 0.24.422, and there are no links on Antox github page.

**Comment by zoff99** [comment] 2017-02-07 20:34
it should be on f-droid antox repo. or you can try the CI build
https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25.1

!! this is a development version !!

**Comment by yurivict** [comment] 2017-02-08 06:34
Actually, file transfers seem to work in antox-0.25.1.

**Comment by iphydf** [comment] 2022-02-04 09:47
File transfers work. If anything more specific and reproducible is broken, please create a new issue.

**Closed by iphydf** 2022-02-04 09:47 UTC
Labels: enhancement, P1, network
