### ISSUE TITLE
The current tox save format is non-portable

### ISSUE THREAD

**Issue by isotoxin** [TokTok/c-toxcore#215] opened 2016-10-27 14:37 UTC
I can't find explicit alignment of SAVED_FRIEND struct
This structure is written into tox_save file as is. That is why very important to provide same alignment of this struct across all clients. What happens if I set default align to 1 byte for toxcore?
Ok, you answer me: "all good guys build toxcore using in-lib scripts and they always get same align"
But I build toxcore using msvc and I'm bad guy. Do you know, that it is very bad practice - save structures to file as is, without portable serialization?

**Comment by GrayHatter** [comment] 2016-10-27 19:54
Toxcore offers a method to get the save data from a function call, and expects that a save file will ONLY be used on the system/device is was created on.

This is a know issue and is waiting for someone to fix it.

**Comment by isotoxin** [comment] 2016-10-27 19:59
> save file will ONLY be used on the system/device is was created on.

No, the problem is deeper. tox_save file can be incompatible across different clients on the same system/platform/device. It depend on default per-project align settings. It is very bad.

**Comment by GrayHatter** [comment] 2016-10-27 20:02
Sorry, I didn't explain what I meant to very well. Toxcore expects to be a system library. not compiled in statically into different clients, by different (incompatible compilers).

Either way thought, you're correct, it's a problem that could/should be fixed.

**Comment by isotoxin** [comment] 2016-10-27 20:17
> Toxcore expects to be a system library

Linux way, right? There is no reason to be a system library on windows, android, or other systems

**Comment by iphydf** [comment] 2016-10-27 20:24
I've taken the liberty to change the issue title to something actionable. I hope this is in line with your intention.

**Comment by dvor** [comment] 2016-10-27 20:37
Also this format should be same for all other implementations of tox protocol (hstox, rust tox, etc.).

**Comment by SkyzohKey** [comment] 2016-10-28 11:55
>There is no reason to be a system library on windows, android, or other systems

@isotoxin Because those OS are broken doesn't mean we have to do shit things. A client running on Windoesn't should simply install `libtoxcore0.dll`, `libtoxencryptsave0.dll` and `toxav0.dll` on the dll's system folder (or any folder + appending the path to `PATH` env variable), making it available for all the others clients the user would like to use in the future, and avoiding stupid lib' duplicates.

Avoiding duplicated libraries means : More disk space for the user, less conflicting versions and simpler way to update Toxcore **globally**

**Comment by isotoxin** [comment] 2016-10-28 15:27
> CAT:enhancement

What?! Enhancement?!
Do you understand the problem?
It just fix of bullshit code of security related software

**Comment by iphydf** [comment] 2016-10-28 15:39
What would you think of an msgpack-based format?

**Comment by GrayHatter** [comment] 2016-10-28 17:54
@isotoxin yes, it's an enhancement. Toxcore was never intended to do that. It's working is it was designed to.

So as far as I see it. You're options are to fix it yourself. Wait until someone else wants to fix it, or pay someone.

I'll convert it to msgpack for you want to pay me 200USD and it'll take 48 to 72 hours after payment is received.

**Comment by uToxingInTox** [comment] 2016-10-28 18:00
>I'll convert it to msgpack for yif you want to pay me 200USD. It'll take 48 to 72 hours after payment is received.

Reminds me of good times when irungentoo was part of tox development. But later he got money and left project. Btw, guys, you can pay me 199.99 and I will fix it in 36-48 hours after payment is received.

**Comment by iphydf** [comment] 2016-10-28 18:15
What would an msgpack-based format look like? The way I see it there are basically two ways of encoding aggregate data structures:

1. Using object arrays and storing the fields in order (pro: more efficient, con: harder to keep backwards and forwards compatible).
2. Using maps with field names (pro: a generic msgpack dump makes more sense, con: uses more space, because field names are repeated all the time).

A space optimisation could be done by providing a field name dictionary and using name indices instead of actual field names in the map. Con: additional complexity.

Thoughts?

**Comment by isotoxin** [comment] 2016-10-28 18:39
Guys, stop!
What da msgpack, what da json, what da portable? What are you talking about? The problem is only **UNSPECIFIED** align of mebers of SAVED_FRIEND structure!
Do you hear about __attribute__ ((packed)) ? No? And know what? You cannot apply this attribute to SAVED_FRIEND, because it correct only with align=8. Is align=8 explicitly defined anywhere? No!
Bullshit code! You have holes in structure that will be written to disk! You have unstable code! This code can be compiled different ways and it will broke compatibility. That is the problem!
Arrgh. Forget...

**Comment by iphydf** [comment] 2016-10-28 18:45
The issue I understand you're having here is that we're writing structs directly from memory to disk, which is unportable. Compiling with different flags, or on different machines, can break save file parsing. This is a portability issue. One solution is to fix the save code to save `SAVED_FRIEND` in the most common format (e.g. LP64 data model) manually. Another solution is to use a binary packing library like msgpack.

**Comment by iphydf** [comment] 2016-10-28 18:47
To preserve compatibility as much as possible, I propose we fix the save code to not memcpy structs to disk, but rather encodes them (with holes) manually. @isotoxin would you like to submit a PR for this change?

**Comment by nurupo** [comment] 2016-10-31 16:26
@SkyzohKey 
>@isotoxin Because those OS are broken doesn't mean we have to do shit things. A client running on Windoesn't should simply install libtoxcore0.dll, libtoxencryptsave0.dll and toxav0.dll on the dll's system folder (or any folder + appending the path to PATH env variable), making it available for all the others clients the user would like to use in the future, and avoiding stupid lib' duplicates.

No, you shouldn't install your .dlls into system folder, that's not the way you do things on Windows. While it's the right way on Linux, on Windows Installing .dlls into the system folder is whe wrong way, i.e. you would be doing "shit things".

@GrayHatter 
>@isotoxin yes, it's an enhancement. Toxcore was never intended to do that. It's working is it was designed to.

You lost me. The save data format is a known issue that should be fixed. The save data **is** broken and if "It's working is it was designed to.", then we should reconsider the broken design.

>So as far as I see it. You're options are to fix it yourself. Wait until someone else wants to fix it, or pay someone.
>I'll convert it to msgpack for yif you want to pay me 200USD. It'll take 48 to 72 hours after payment is received.

Why are you so rude? @isotoxin opened a valid issue.

**Comment by GrayHatter** [comment] 2016-10-31 17:37
@nurupo agreed, we should reconsider the design, because it IS broken, and it's doing only what it's meant to and nothing more.

That's why @iphydf suggested different formats, if we're fixing it, we should fix it once.

**Closed** 2016-11-21 00:59 UTC
Labels: CAT:enhancement
