### ISSUE TITLE
version 0.1.5 != 0.1.6 in tox.h ?

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#478] opened 2017-02-17 11:30 UTC
https://github.com/TokTok/c-toxcore/blob/master/toxcore/tox.h#L183

is this correct?

**Comment by nurupo** [comment] 2017-02-17 11:55
Closing as a duplicate of https://github.com/TokTok/c-toxcore/issues/474.

**Closed by nurupo** 2017-02-17 11:55 UTC
