### ISSUE TITLE
NGC: Disentangle onion_client and group chats

### ISSUE THREAD

**Issue by iphydf** [TokTok/c-toxcore#1176] opened 2018-09-18 22:34 UTC
NGC threaded group chats through onion client, so there is now a mutual dependency between the two. We should try to find a way to provide functionality from onion_client to NGC without explicit calls into NGC code from the onion code.

**Comment by JFreegman** [comment] 2022-03-06 16:59
Duplicate of https://github.com/TokTok/c-toxcore/issues/2139

**Closed by JFreegman** 2022-03-06 16:59 UTC
Labels: P3
