### ISSUE TITLE
3 warnings compiling c-toxcore master (for Android)

### ISSUE THREAD

**Issue by zoff99** [TokTok/c-toxcore#458] opened 2017-01-23 18:52 UTC
```
  CC       ../toxcore/libtoxcore_la-Messenger.lo
/home/ubuntu/c-toxcore/build/../toxcore/Messenger.c:2246:28: warning: 
      comparison of constant 256 with expression of type 'uint8_t'
      (aka 'unsigned char') is always false
      [-Wtautological-constant-out-of-range-compare]
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
                ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/c-toxcore/build/../toxcore/Messenger.c:2306:28: warning: 
      comparison of constant 256 with expression of type 'uint8_t'
      (aka 'unsigned char') is always false
      [-Wtautological-constant-out-of-range-compare]
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
                ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/c-toxcore/build/../toxcore/Messenger.c:2326:28: warning: 
      comparison of constant 256 with expression of type 'uint8_t'
      (aka 'unsigned char') is always false
      [-Wtautological-constant-out-of-range-compare]
            if (filenumber >= MAX_CONCURRENT_FILE_PIPES) {
                ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zoff99** [comment] 2017-01-24 11:52
comparison is always false

**Comment by zoff99** [comment] 2017-01-24 11:56
sometimes its defined as
```
uint8_t filenumber
```
other times as
```
uint32_t filenumber
```

?

**Comment by iphydf** [comment] 2017-01-24 13:18
Duplicate of #352.

**Closed by iphydf** 2017-01-24 13:18 UTC
