### ISSUE TITLE
Feature request: ability to specify tox-bootstrapd listen address/interface

### ISSUE THREAD

**Issue by cryptogospod** [TokTok/c-toxcore#1692] opened 2021-09-16 20:52 UTC
Hi, I'm a maintainer of several `tox-bootstrapd` nodes. On servers with multiple IPs, it would be very useful to have the ability to specify an address or an interface for `tox-bootstrapd` to listen on. By default, it binds to all interfaces. It would make it simpler to run multiple nodes on different interfaces, as well as manage firewall rules.

**Comment by kurnevsky** [comment] 2021-09-24 18:06
@cryptogospod you can check our tox node written in rust: https://github.com/tox-rs/tox-node - it has this feature :)

**Comment by iphydf** [comment] 2022-02-05 01:10
Duplicate of #259.

**Closed by iphydf** 2022-02-05 01:10 UTC
Labels: P3
